- hosts: targets
  remote_user: root
  gather_facts: yes
  roles:
    - { 
      role: mailu,
        ipv6_enabled: 'false',
        create_stack_network: true,
        stack_network_name: "mailu_net",
        stack_subnet: "10.10.16.0/24",
        record_mx_create: false,
        record_rdns_create: false,
        record_dkim_dmarc_create: false,
        dns_create: false,
        dns_update: false,
        rdns_cloud: false,
        auth_provider_domain: 'key.{{ domain }}.com',
        keycloak_redirect: "https://{{ domain }}/",
        auth_bypass: "false",
        include_auth: false,
        tags: [ mailu ]
      }