NGINX := $$(docker ps -a | awk '{print $$NF}' | grep -w "{{ nginx_stack}}_nginx-proxy\.*")
ADMIN := $$(docker ps -a | awk '{print $$NF}' | grep -w "{{ deploy_name }}_admin\.*")
POSTFIX := $$(docker ps -a | awk '{print $$NF}' | grep -w "{{ deploy_name }}_smtp\.*")
FRONT := $$(docker ps -a | awk '{print $$NF}' | grep -w "mailu_front\.*")

initadmin:
	docker exec $(FRONT) /bin/sh -c "./config.py && nginx -s reload"

rm:
	docker stack rm {{ deploy_name }}

cp:
	docker cp $(ADMIN):/app/mailu/manage.py {{ user_path }}/mailu

deploy:
	docker stack deploy -c docker-compose.yml {{ deploy_name }} && docker exec -it $(NGINX) nginx -s reload && sleep 20s && make initadmin

createadmin:
	docker exec $(ADMIN) flask {{ deploy_name }} admin admin {{ nginx_domain }} {{ mailu_admin_pw }}

genkeys:
	docker exec $(ADMIN) flask {{ deploy_name }} genkeys {{ nginx_domain }}

installcurl:
	docker exec -i $(POSTFIX) /bin/sh -c "apk add --no-cache curl"

ps:
	docker stack ps {{ deploy_name }} --no-trunc